name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Checkout with submodules.
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@v1

      - name: Create build environment
        run: cmake -E make_directory ${{github.workspace}}/vendors/raylib/build

      - name: Get dependencies
        run: sudo apt update && sudo apt install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libopengl-dev mesa-common-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/vendors/raylib/build
        run: cmake ../ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/vendors/raylib/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
